# Generated by Django 5.2.6 on 2025-09-27 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('status', models.CharField(choices=[('planned', 'Planowany'), ('active', 'Aktywny'), ('on_hold', 'Wstrzymany'), ('done', 'Zakończony'), ('archived', 'Zarchiwizowany')], default='planned', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(choices=[(1, 'Niski'), (2, 'Średni'), (3, 'Wysoki'), (4, 'Krytyczny')], default=2, verbose_name='Priorytet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
