/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './templates/**/*.html',
    './**/templates/**/*.html',
    './static/**/*.js',
  ],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      "light", 
      "dark", 
      "cupcake", 
      "bumblebee", 
      "emerald", 
      "corporate", 
      "synthwave", 
      "retro", 
      "cyberpunk", 
      "valentine", 
      "halloween", 
      "garden", 
      "forest", 
      "aqua", 
      "lofi", 
      "pastel", 
      "fantasy", 
      "wireframe", 
      "black", 
      "luxury", 
      "dracula", 
      "cmyk", 
      "autumn", 
      "business", 
      "acid", 
      "lemonade", 
      "night", 
      "coffee", 
      "winter",
      {
        workly: {
          // Wersja 1: Jasny motyw (obecny)
          "primary": "#9333ea",
          "primary-focus": "#7c3aed",
          "primary-content": "#ffffff",
          "secondary": "#764ba2",
          "secondary-focus": "#6d28d9",
          "secondary-content": "#ffffff",
          "accent": "#a855f7",
          "accent-focus": "#9333ea",
          "accent-content": "#ffffff",
          "neutral": "#1e1b4b",
          "neutral-focus": "#312e81",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f3f4f6",
          "base-300": "#e5e7eb",
          "base-content": "#1f2937",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#10b981",
          "success-content": "#ffffff",
          "warning": "#f59e0b",
          "warning-content": "#ffffff",
          "error": "#ef4444",
          "error-content": "#ffffff",
        },
        worklyDark: {
          // Wersja 2: Ciemny motyw
          "primary": "#a855f7",
          "primary-focus": "#9333ea",
          "primary-content": "#ffffff",
          "secondary": "#764ba2",
          "secondary-focus": "#6d28d9",
          "secondary-content": "#ffffff",
          "accent": "#c084fc",
          "accent-focus": "#a855f7",
          "accent-content": "#1e1b4b",
          "neutral": "#312e81",
          "neutral-focus": "#1e1b4b",
          "neutral-content": "#ffffff",
          "base-100": "#1e1b4b",
          "base-200": "#312e81",
          "base-300": "#4c1d95",
          "base-content": "#f3e8ff",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#10b981",
          "success-content": "#ffffff",
          "warning": "#f59e0b",
          "warning-content": "#ffffff",
          "error": "#ef4444",
          "error-content": "#ffffff",
        },
        worklyLight: {
          // Jasny motyw komplementarny do Synthwave
          "primary": "#ff006e",
          "primary-focus": "#e60063",
          "primary-content": "#ffffff",
          "secondary": "#8338ec",
          "secondary-focus": "#7209b7",
          "secondary-content": "#ffffff",
          "accent": "#3a86ff",
          "accent-focus": "#2d6ef5",
          "accent-content": "#ffffff",
          "neutral": "#1a1a2e",
          "neutral-focus": "#0f0f1e",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f8f9fa",
          "base-300": "#e9ecef",
          "base-content": "#1a1a2e",
          "info": "#3a86ff",
          "info-content": "#ffffff",
          "success": "#06ffa5",
          "success-content": "#1a1a2e",
          "warning": "#ffbe0b",
          "warning-content": "#1a1a2e",
          "error": "#ff006e",
          "error-content": "#ffffff",
        },
        worklyPurple: {
          // Wersja 4: Intensywny fioletowy motyw
          "primary": "#7c3aed",
          "primary-focus": "#6d28d9",
          "primary-content": "#ffffff",
          "secondary": "#9333ea",
          "secondary-focus": "#7c3aed",
          "secondary-content": "#ffffff",
          "accent": "#a855f7",
          "accent-focus": "#9333ea",
          "accent-content": "#ffffff",
          "neutral": "#4c1d95",
          "neutral-focus": "#5b21b6",
          "neutral-content": "#ffffff",
          "base-100": "#faf5ff",
          "base-200": "#f3e8ff",
          "base-300": "#e9d5ff",
          "base-content": "#581c87",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#10b981",
          "success-content": "#ffffff",
          "warning": "#f59e0b",
          "warning-content": "#ffffff",
          "error": "#ef4444",
          "error-content": "#ffffff",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
}

