# Generated by Django 5.2.6 on 2025-09-27 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sort_index',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Indeks sortowania'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Do zrobienia'), ('in_progress', 'W toku'), ('review', 'Weryfikacja'), ('done', 'Zrobione'), ('blocked', 'Zablokowane')], default='todo', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FS', 'Finish→Start'), ('SS', 'Start→Start'), ('FF', 'Finish→Finish'), ('SF', 'Start→Finish')], default='FS', max_length=2)),
                ('lag_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_predecessor', to='tasks.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_successor', to='tasks.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor', 'type'), name='uniq_dependency_edge_type'), models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='no_self_dependency')],
            },
        ),
    ]
