# Generated by Django 5.2.6 on 2025-09-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_sort_index_alter_task_status_dependency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependency',
            options={'verbose_name': 'Zależność', 'verbose_name_plural': 'Zależności'},
        ),
        migrations.AlterField(
            model_name='dependency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='lag_days',
            field=models.IntegerField(default=0, verbose_name='Liczba dni opóźnienia'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='predecessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_predecessor', to='tasks.task', verbose_name='Poprzednik'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='successor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_successor', to='tasks.task', verbose_name='Następnik'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='type',
            field=models.CharField(choices=[('FS', 'Koniec→Start'), ('SS', 'Start→Start'), ('FF', 'Koniec→Koniec'), ('SF', 'Start→Koniec')], default='FS', max_length=2, verbose_name='Typ zależności'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
    ]
