# Generated by Django 6.0 on 2025-12-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0003_alter_dependency_options_alter_dependency_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependency',
            options={'ordering': ['id'], 'verbose_name': 'Zależność', 'verbose_name_plural': 'Zależności'},
        ),
        migrations.AlterField(
            model_name='dependency',
            name='predecessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_predecessor', to='tasks.task', verbose_name='Poprzednik'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='successor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_successor', to='tasks.task', verbose_name='Następnik'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tasks.task', verbose_name='Zadanie nadrzędne'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.project', verbose_name='Projekt'),
        ),
    ]
